/* Ernos Zdravstvena Njega - patient important contacts */
(function(){
  if(window.__ernosContactsLoaded)return;window.__ernosContactsLoaded=true;
  var timer=null;
  function $(s){return document.querySelector(s);} 
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch]||ch;});}
  function token(){try{return(window.state&&window.state.token)||sessionStorage.getItem('ernosToken')||localStorage.getItem('ernosToken')||'';}catch(e){return'';}}
  function api(path,opt){opt=opt||{};var h={'Content-Type':'application/json'};var t=token();if(t)h.Authorization='Bearer '+t;return fetch(location.origin+path,{method:opt.method||'GET',headers:h,body:opt.body?JSON.stringify(opt.body):undefined}).then(function(r){return r.text().then(function(txt){var j=null;try{j=txt?JSON.parse(txt):null;}catch(e){}if(!r.ok)throw new Error((j&&(j.error||j.detail||j.message))||txt||('HTTP '+r.status));return j||{};});});}
  function params(){return new URLSearchParams((location.hash.split('?')[1]||''));}
  function nav(){var n=$('#nav');if(!n||$('#navContacts'))return;var a=document.createElement('a');a.id='navContacts';a.href='#contacts';a.textContent='Kontakti';n.appendChild(a);}
  function setTitle(t){var c=$('#crumbs');if(c)c.textContent=t;document.title='Ernos Zdravstvena Njega - '+t;}
  function label(x){return esc(x.contact_type||'Kontakt')+(x.is_primary?' · glavni':'')+(x.priority?(' · '+esc(x.priority)):'');}
  function item(x,global){return '<div style="border:1px solid var(--border);border-radius:12px;padding:10px;background:#fff"><strong>'+esc(x.name||x.phone||'Kontakt')+'</strong><div class="muted">'+label(x)+'</div>'+(global?'<div class="muted">Pacijent: '+esc(x.patient_name||'')+' · '+esc(x.address||'')+'</div>':'')+(x.phone?'<div>Telefon: <a href="tel:'+esc(x.phone)+'">'+esc(x.phone)+'</a></div>':'')+(x.email?'<div>Email: <a href="mailto:'+esc(x.email)+'">'+esc(x.email)+'</a></div>':'')+(x.note?'<div class="muted">'+esc(x.note)+'</div>':'')+'<div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap">'+(global?'<a class="btn small ghost" href="#patient?id='+esc(x.patient_id)+'">Profil</a>':'')+'<button class="btn small ghost" data-del-contact="'+esc(x.id)+'" type="button">Ukloni</button></div></div>';}
  function listHtml(items,global){if(!items||!items.length)return'<div class="empty">Nema kontakata.</div>';var html='<div style="display:grid;gap:8px">';for(var i=0;i<items.length;i++)html+=item(items[i],global);return html+'</div>';}
  function profileCard(){nav();var route=(location.hash||'').split('?')[0];if(route!=='#patient')return;var id=params().get('id')||'';var view=$('#view');if(!id||!view||$('#contactsCard'))return;var box=document.createElement('div');box.className='card';box.id='contactsCard';box.innerHTML='<h3>Važni kontakti</h3><p class="muted">Liječnik, ljekarna, hitni kontakt, osoba s ključem, susjed/skrbnik.</p><form id="contactForm" class="grid cols-3" autocomplete="off"><div><label>Vrsta</label><select name="contact_type"><option>Liječnik</option><option>Ljekarna</option><option>Hitni kontakt</option><option>Obitelj</option><option>Osoba s ključem</option><option>Susjed/skrbnik</option><option>Patronaža</option><option>Drugo</option></select></div><div><label>Ime / naziv</label><input name="name"></div><div><label>Telefon</label><input name="phone"></div><div><label>Email</label><input name="email"></div><div><label>Prioritet</label><select name="priority"><option>normal</option><option>srednje</option><option>visoko</option><option>hitno</option></select></div><label style="display:flex;gap:8px;align-items:center;margin-top:24px"><input name="is_primary" type="checkbox" style="width:auto"> Glavni kontakt</label><div style="grid-column:1/-1"><label>Napomena</label><textarea name="note" rows="2"></textarea></div><div style="grid-column:1/-1;display:flex;gap:8px;align-items:center;flex-wrap:wrap"><button class="btn" type="submit">Dodaj kontakt</button><button class="btn ghost" id="refreshContacts" type="button">Osvježi</button><span id="contactsMsg" class="muted"></span></div></form><div id="contactsList" style="margin-top:12px"></div>';
    var target=$('#patientSummaryCard')||$('#patientSafetyCard')||$('#patientEditCard')||$('#realScanCard');if(target&&target.parentNode)target.parentNode.insertBefore(box,target);else view.appendChild(box);
    var form=$('#contactForm'),msg=$('#contactsMsg');function load(){var wrap=$('#contactsList');if(!wrap)return;wrap.innerHTML='<div class="muted">Učitavanje...</div>';api('/api/care/patients/'+encodeURIComponent(id)+'/contacts').then(function(d){wrap.innerHTML=listHtml(d.items||[],false);}).catch(function(e){wrap.innerHTML='<div class="alert err">Greška: '+esc(e.message||e)+'</div>';});}
    if(form)form.onsubmit=function(ev){ev.preventDefault();var fd=new FormData(form),body={};fd.forEach(function(v,k){body[k]=v;});body.is_primary=!!fd.get('is_primary');api('/api/care/patients/'+encodeURIComponent(id)+'/contacts',{method:'POST',body:body}).then(function(){form.reset();if(msg)msg.textContent='Kontakt dodan.';load();}).catch(function(e){if(msg)msg.textContent='Greška: '+(e.message||e);});};
    var ref=$('#refreshContacts');if(ref)ref.onclick=load;box.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('[data-del-contact]'):null;if(!b)return;if(!confirm('Ukloniti kontakt?'))return;api('/api/care/contacts/'+encodeURIComponent(b.getAttribute('data-del-contact')),{method:'DELETE'}).then(load).catch(function(e){alert('Greška: '+(e.message||e));});});load();}
  function contactsPage(){nav();var route=(location.hash||'').split('?')[0];if(route!=='#contacts')return;var view=$('#view');if(!view)return;setTitle('Kontakti');view.innerHTML='<div class="card"><h2>Kontakti</h2><p class="muted">Svi važni kontakti po pacijentima.</p><button class="btn ghost" id="refreshAllContacts" type="button">Osvježi</button></div><div class="card"><div id="allContactsList" class="muted">Učitavanje...</div></div>';function load(){api('/api/care/contacts').then(function(d){var items=d.items||[];$('#allContactsList').innerHTML=listHtml(items,true);}).catch(function(e){$('#allContactsList').innerHTML='<div class="alert err">Greška: '+esc(e.message||e)+'</div>';});}var b=$('#refreshAllContacts');if(b)b.onclick=load;var list=$('#allContactsList');if(list)list.addEventListener('click',function(ev){var btn=ev.target&&ev.target.closest?ev.target.closest('[data-del-contact]'):null;if(!btn)return;if(!confirm('Ukloniti kontakt?'))return;api('/api/care/contacts/'+encodeURIComponent(btn.getAttribute('data-del-contact')),{method:'DELETE'}).then(load).catch(function(e){alert('Greška: '+(e.message||e));});});load();}
  function run(){profileCard();contactsPage();}
  function schedule(){nav();if(timer)clearTimeout(timer);timer=setTimeout(function(){timer=null;run();},250);} 
  window.addEventListener('hashchange',schedule);document.addEventListener('DOMContentLoaded',schedule);try{new MutationObserver(function(){nav();}).observe(document.documentElement,{childList:true,subtree:true});}catch(e){}if(document.readyState!=='loading')schedule();
})();
