/* Ernos Zdravstvena Njega - incident log */
(function(){
  var timer=null;
  function $(s){return document.querySelector(s);}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch]||ch;});}
  function token(){try{return (window.state&&window.state.token)||sessionStorage.getItem('ernosToken')||localStorage.getItem('ernosToken')||'';}catch(e){return '';}}
  function api(path,opt){opt=opt||{};var h={'Content-Type':'application/json'};var t=token();if(t)h.Authorization='Bearer '+t;return fetch(location.origin+path,{method:opt.method||'GET',headers:h,body:opt.body?JSON.stringify(opt.body):undefined}).then(function(r){return r.text().then(function(txt){var j=null;try{j=txt?JSON.parse(txt):null;}catch(e){}if(!r.ok)throw new Error((j&&(j.error||j.detail||j.message))||txt||('HTTP '+r.status));return j||{};});});}
  function params(){return new URLSearchParams((location.hash.split('?')[1]||''));}
  function fmt(v){if(!v)return '-';try{return new Date(v).toLocaleString('hr-HR');}catch(e){return String(v);}}
  function full(x){return String((x.first_name||'')+' '+(x.last_name||'')).trim()||'Pacijent';}
  function title(t){var c=$('#crumbs');if(c)c.textContent=t;document.title='Ernos Zdravstvena Njega - '+t;}
  function sevLabel(s){s=String(s||'medium');if(s==='high')return 'Visoko';if(s==='low')return 'Nisko';return 'Srednje';}
  function stLabel(s){return String(s||'open')==='closed'?'Zatvoreno':'Otvoreno';}
  function nav(){var n=$('#nav');if(!n||$('#navIncidents'))return;var a=document.createElement('a');a.id='navIncidents';a.href='#incidents';a.textContent='Događaji';n.appendChild(a);}
  function itemHtml(x){var name=full(x);var scan=x.scan_code?('/#scan?t='+encodeURIComponent(x.scan_code)):'';var h='<div style="border:1px solid var(--border);border-radius:14px;padding:12px;background:#fff">';h+='<div style="display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap"><div><strong>'+esc(x.incident_type||'Događaj')+'</strong><div class="muted">'+esc(name)+' · '+esc(fmt(x.created_at))+'</div></div><span class="tag">'+esc(sevLabel(x.severity))+' · '+esc(stLabel(x.status))+'</span></div>';h+='<p style="margin-top:8px">'+esc(x.description||'')+'</p>';if(x.action_taken)h+='<p class="muted"><strong>Poduzeto:</strong> '+esc(x.action_taken)+'</p>';if(x.follow_up)h+='<p class="muted"><strong>Follow-up:</strong> '+esc(x.follow_up)+'</p>';h+='<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:8px">';h+='<a class="btn small ghost" href="#patient?id='+esc(x.patient_id)+'">Profil</a>';if(scan)h+='<a class="btn small" href="'+esc(scan)+'">Scan</a>';if(String(x.status)!=='closed')h+='<button class="btn small" data-close-incident="'+esc(x.id)+'" type="button">Zatvori</button>';h+='</div></div>';return h;}
  function ensureProfileCard(){var route=(location.hash||'').split('?')[0];if(route!=='#patient')return;var id=params().get('id')||'';if(!id||$('#incidentsCard'))return;var view=$('#view');if(!view)return;var box=document.createElement('div');box.className='card';box.id='incidentsCard';box.innerHTML='<h3>Izvanredni događaji</h3><p class="muted">Pad, pogoršanje, odbijena njega, pacijent nije doma, problem s ranom, kontakt liječnika ili obitelji.</p><form id="incidentForm" class="grid cols-2"><div><label>Vrsta događaja</label><select name="incident_type"><option>Pad</option><option>Pogoršanje stanja</option><option>Pacijent nije doma</option><option>Odbijena njega</option><option>Problem s ranom</option><option>Poziv liječniku</option><option>Poziv obitelji</option><option>Drugo</option></select></div><div><label>Ozbiljnost</label><select name="severity"><option value="medium">Srednje</option><option value="high">Visoko</option><option value="low">Nisko</option></select></div><div style="grid-column:1/-1"><label>Opis</label><textarea name="description" rows="3" required></textarea></div><div style="grid-column:1/-1"><label>Što je poduzeto</label><textarea name="action_taken" rows="2"></textarea></div><div style="grid-column:1/-1"><label>Follow-up</label><textarea name="follow_up" rows="2"></textarea></div><div style="grid-column:1/-1;display:flex;gap:8px;align-items:center;flex-wrap:wrap"><button class="btn" type="submit">Spremi događaj</button><a class="btn ghost" href="#incidents?patient_id='+esc(id)+'">Svi događaji</a><span id="incidentMsg" class="muted"></span></div></form><div id="patientIncidentsList" style="margin-top:12px"></div>';view.appendChild(box);var form=$('#incidentForm');if(form){form.onsubmit=function(ev){ev.preventDefault();var fd=new FormData(form);var body={};fd.forEach(function(v,k){body[k]=v;});var msg=$('#incidentMsg');if(msg)msg.textContent='Spremam...';api('/api/care/patients/'+encodeURIComponent(id)+'/incidents',{method:'POST',body:body}).then(function(){form.reset();if(msg)msg.textContent='Spremljeno.';loadPatient(id);}).catch(function(e){if(msg)msg.textContent='Greška: '+(e.message||e);});};}loadPatient(id);}
  function loadPatient(id){var el=$('#patientIncidentsList');if(!el)return;api('/api/care/patients/'+encodeURIComponent(id)+'/incidents').then(function(d){var items=(d.items||[]).slice(0,5);if(!items.length){el.innerHTML='<div class="empty">Nema evidentiranih događaja.</div>';return;}var h='<div style="display:grid;gap:8px">';for(var i=0;i<items.length;i++)h+=itemHtml(items[i]);el.innerHTML=h+'</div>';}).catch(function(e){el.innerHTML='<div class="alert err">Greška: '+esc(e.message||e)+'</div>';});}
  function renderPage(){var route=(location.hash||'').split('?')[0];if(route!=='#incidents')return;var view=$('#view');if(!view)return;title('Događaji');var p=params();var patientId=p.get('patient_id')||'';view.innerHTML='<div class="card"><h2>Događaji</h2><p class="muted">Pregled izvanrednih događaja i incidenata.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn ghost" id="refreshIncidents" type="button">Osvježi</button><select id="incidentStatus" style="max-width:220px"><option value="open">Otvoreno</option><option value="all">Sve</option><option value="closed">Zatvoreno</option></select></div></div><div class="card"><div id="incidentsList" class="empty">Učitavanje...</div></div>';function load(){var s=($('#incidentStatus')&&$('#incidentStatus').value)||'open';var url='/api/care/incidents?status='+encodeURIComponent(s);if(patientId)url+='&patient_id='+encodeURIComponent(patientId);api(url).then(function(d){var items=d.items||[];var el=$('#incidentsList');if(!items.length){el.innerHTML='<div class="empty">Nema događaja za ovaj filter.</div>';return;}var h='<div style="display:grid;gap:10px">';for(var i=0;i<items.length;i++)h+=itemHtml(items[i]);el.innerHTML=h+'</div>';}).catch(function(e){$('#incidentsList').innerHTML='<div class="alert err">Greška: '+esc(e.message||e)+'</div>';});}var r=$('#refreshIncidents');if(r)r.onclick=load;var st=$('#incidentStatus');if(st)st.onchange=load;view.onclick=function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('[data-close-incident]'):null;if(!b)return;var note=prompt('Follow-up / zaključak:', '')||'';api('/api/care/incidents/'+encodeURIComponent(b.getAttribute('data-close-incident')),{method:'PATCH',body:{status:'closed',follow_up:note}}).then(load).catch(function(e){alert('Greška: '+(e.message||e));});};load();}
  function run(){nav();ensureProfileCard();renderPage();}
  function schedule(){if(timer)clearTimeout(timer);timer=setTimeout(function(){timer=null;run();},250);}
  window.addEventListener('hashchange',schedule);document.addEventListener('DOMContentLoaded',schedule);try{new MutationObserver(function(){nav();ensureProfileCard();}).observe(document.documentElement,{childList:true,subtree:true});}catch(e){}if(document.readyState!=='loading')schedule();
})();
