/* Ernos Zdravstvena Njega - patient supplies addon */
(function(){
  if(window.__ernosSuppliesAddonLoaded)return;
  window.__ernosSuppliesAddonLoaded=true;
  var timer=null;
  function $(s){return document.querySelector(s);}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch]||ch;});}
  function token(){try{return(window.state&&window.state.token)||sessionStorage.getItem('ernosToken')||localStorage.getItem('ernosToken')||'';}catch(e){return'';}}
  function api(path,opt){opt=opt||{};var h={'Content-Type':'application/json'};var t=token();if(t)h.Authorization='Bearer '+t;return fetch(location.origin+path,{method:opt.method||'GET',headers:h,body:opt.body?JSON.stringify(opt.body):undefined}).then(function(r){return r.text().then(function(txt){var j=null;try{j=txt?JSON.parse(txt):null;}catch(e){}if(!r.ok)throw new Error((j&&(j.error||j.detail||j.message))||txt||('HTTP '+r.status));return j||{};});});}
  function params(){return new URLSearchParams((location.hash.split('?')[1]||''));}
  function setTitle(t){var c=$('#crumbs');if(c)c.textContent=t;document.title='Ernos Zdravstvena Njega - '+t;}
  function statusLabel(s){if(s==='order')return 'Naručiti';if(s==='low')return 'Nisko';return 'OK';}
  function patientName(x){return String((x.first_name||'')+' '+(x.last_name||'')).trim()||'Pacijent';}
  function nav(){var n=$('#nav');if(!n||$('#navSupplies'))return;var a=document.createElement('a');a.id='navSupplies';a.href='#supplies';a.textContent='Materijali';n.appendChild(a);}
  function card(x,global){return '<div style="border:1px solid var(--border);border-radius:14px;padding:12px;background:#fff">'+(global?'<strong>'+esc(patientName(x))+'</strong><div class="muted">'+esc(x.address||'')+'</div>':'')+'<div style="margin-top:6px"><strong>'+esc(x.item_name||'-')+'</strong> <span class="tag">'+esc(statusLabel(x.status))+'</span></div><div class="muted">Količina: '+esc(x.quantity_text||'-')+(x.location_note?' · Lokacija: '+esc(x.location_note):'')+'</div>'+(x.note?'<div style="margin-top:6px">'+esc(x.note)+'</div>':'')+'<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:8px">'+(global&&x.patient_id?'<a class="btn small ghost" href="#patient?id='+esc(x.patient_id)+'">Profil</a>':'')+'<button class="btn small ghost" data-supply-status="'+esc(x.id)+'" data-status="ok">OK</button><button class="btn small ghost" data-supply-status="'+esc(x.id)+'" data-status="low">Nisko</button><button class="btn small" data-supply-status="'+esc(x.id)+'" data-status="order">Naručiti</button></div></div>';}
  function attachStatus(root,refresh){Array.prototype.forEach.call(root.querySelectorAll('[data-supply-status]'),function(b){b.onclick=function(){b.disabled=true;api('/api/care/supplies/'+encodeURIComponent(b.getAttribute('data-supply-status')),{method:'PATCH',body:{status:b.getAttribute('data-status')}}).then(refresh).catch(function(e){alert('Greška: '+(e.message||e));b.disabled=false;});};});}
  function renderPatient(id){var view=$('#view');if(!view||!id||$('#suppliesCard'))return;var box=document.createElement('div');box.className='card';box.id='suppliesCard';box.innerHTML='<h3>Materijali / oprema</h3><p class="muted">Što treba biti dostupno kod pacijenta ili ponijeti na teren.</p><form id="supplyForm" class="grid cols-3"><div><label>Naziv</label><input name="item_name" placeholder="Obloga, rukavice, fiziološka..." required></div><div><label>Količina</label><input name="quantity_text" placeholder="npr. 5 kom"></div><div><label>Status</label><select name="status"><option value="ok">OK</option><option value="low">Nisko</option><option value="order">Naručiti</option></select></div><div><label>Lokacija</label><input name="location_note" placeholder="kod pacijenta / torba / ormarić"></div><div style="grid-column:span 2"><label>Napomena</label><input name="note"></div><div style="grid-column:1/-1"><button class="btn" type="submit">Dodaj materijal</button> <a class="btn ghost" href="#supplies">Svi materijali</a> <span id="supplyMsg" class="muted"></span></div></form><div id="suppliesList" style="margin-top:12px"></div>';var target=$('#patientSummaryCard')||$('#careLogCard')||$('#incidentCard')||$('#taskCard')||$('#realScanCard');if(target&&target.parentNode)target.parentNode.insertBefore(box,target.nextSibling);else view.appendChild(box);function load(){api('/api/care/patients/'+encodeURIComponent(id)+'/supplies').then(function(d){var items=d.items||[];$('#suppliesList').innerHTML=items.length?'<div style="display:grid;gap:8px">'+items.map(function(x){return card(x,false);}).join('')+'</div>':'<div class="empty">Nema upisanih materijala.</div>';attachStatus(box,load);}).catch(function(e){$('#suppliesList').innerHTML='<div class="alert err">Greška: '+esc(e.message||e)+'</div>';});}var f=$('#supplyForm');f.onsubmit=function(ev){ev.preventDefault();var fd=new FormData(f),body={};fd.forEach(function(v,k){body[k]=v;});api('/api/care/patients/'+encodeURIComponent(id)+'/supplies',{method:'POST',body:body}).then(function(){f.reset();$('#supplyMsg').textContent='Spremljeno.';load();}).catch(function(e){$('#supplyMsg').textContent='Greška: '+(e.message||e);});};load();}
  function renderGlobal(){var view=$('#view');if(!view)return;setTitle('Materijali');view.innerHTML='<div class="card"><h2>Materijali</h2><p class="muted">Pregled materijala i opreme, posebno ono što je nisko ili treba naručiti.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="needSupplies">Nisko / naručiti</button><button class="btn ghost" id="allSupplies">Sve</button></div></div><div class="card"><div id="suppliesGlobalList" class="muted">Učitavanje...</div></div>';function load(status){api('/api/care/supplies'+(status?'?status='+encodeURIComponent(status):'')).then(function(d){var items=d.items||[];var el=$('#suppliesGlobalList');el.innerHTML=items.length?'<div style="display:grid;gap:10px">'+items.map(function(x){return card(x,true);}).join('')+'</div>':'<div class="empty">Nema materijala za prikaz.</div>';attachStatus(view,function(){load(status);});}).catch(function(e){$('#suppliesGlobalList').innerHTML='<div class="alert err">Greška: '+esc(e.message||e)+'</div>';});}$('#needSupplies').onclick=function(){load('needed');};$('#allSupplies').onclick=function(){load('');};load('needed');}
  function run(){nav();var r=(location.hash||'').split('?')[0];if(r==='#patient')renderPatient(params().get('id')||'');if(r==='#supplies')renderGlobal();}
  function schedule(){if(timer)clearTimeout(timer);timer=setTimeout(function(){timer=null;run();},250);}
  window.addEventListener('hashchange',schedule);document.addEventListener('DOMContentLoaded',schedule);try{new MutationObserver(function(){nav();schedule();}).observe(document.documentElement,{childList:true,subtree:true});}catch(e){}if(document.readyState!=='loading')schedule();
})();
