/* Ernos - follow-up tasks */
(function(){
var timer=null,profile='';
function $(s){return document.querySelector(s)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})}
function tok(){try{return (window.state&&window.state.token)||sessionStorage.getItem('ernosToken')||localStorage.getItem('ernosToken')||''}catch(e){return ''}}
function api(p,o){o=o||{};var h={'Content-Type':'application/json'},t=tok();if(t)h.Authorization='Bearer '+t;return fetch(location.origin+p,{method:o.method||'GET',headers:h,body:o.body?JSON.stringify(o.body):undefined}).then(function(r){return r.text().then(function(x){var j=null;try{j=x?JSON.parse(x):null}catch(e){}if(!r.ok)throw new Error((j&&(j.error||j.detail))||x||('HTTP '+r.status));return j||{}})})}
function q(){return new URLSearchParams((location.hash.split('?')[1]||''))}
function fmt(v){if(!v)return '-';try{return new Date(v).toLocaleString('hr-HR')}catch(e){return String(v)}}
function val(id){var n=document.getElementById(id);return n?n.value:''}
function nav(){var n=$('#nav');if(!n||$('#navTasks'))return;var a=document.createElement('a');a.id='navTasks';a.href='#tasks';a.textContent='Zadaci';n.insertBefore(a,n.firstChild)}
function name(x){return x.patient_name||String((x.first_name||'')+' '+(x.last_name||'')).trim()||'Pacijent'}
function box(x,pat){var html='<div style="border:1px solid var(--border);border-radius:12px;padding:10px;background:#fff">';if(pat)html+='<strong>'+esc(name(x))+'</strong><div class="muted">'+esc(x.address||'')+'</div>';html+='<div><strong>'+esc(x.title||'Zadatak')+'</strong></div><div class="muted">Prioritet: '+esc(x.priority||'normal')+(x.due_at?' · Rok: '+esc(fmt(x.due_at)):'')+'</div>'+(x.details?'<div>'+esc(x.details)+'</div>':'')+'<div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap">';if(x.scan_url)html+='<a class="btn small" href="'+esc(x.scan_url)+'">Scan</a>';if(x.patient_id)html+='<a class="btn small ghost" href="#patient?id='+esc(x.patient_id)+'">Profil</a>';html+='<button class="btn small taskDone" data-id="'+esc(x.id)+'" type="button">Odrađeno</button></div></div>';return html}
function bind(cb){document.querySelectorAll('.taskDone').forEach(function(b){b.onclick=function(){api('/api/care/tasks/'+encodeURIComponent(b.getAttribute('data-id')),{method:'PATCH',body:{status:'done'}}).then(cb).catch(function(e){alert('Greška: '+(e.message||e))})}})}
function page(){nav();if((location.hash||'').split('?')[0]!=='#tasks')return;var v=$('#view');if(!v)return;if($('#crumbs'))$('#crumbs').textContent='Zadaci';v.innerHTML='<div class="card"><h2>Zadaci</h2><p class="muted">Otvoreni zadaci za sljedeće posjete.</p><div id="tasksList">Učitavanje...</div></div>';api('/api/care/tasks?status=open').then(function(d){var it=d.items||[],h='';if(!it.length)h='<div class="empty">Nema otvorenih zadataka.</div>';else{h='<div style="display:grid;gap:10px">';for(var i=0;i<it.length;i++)h+=box(it[i],true);h+='</div>'}$('#tasksList').innerHTML=h;bind(page)}).catch(function(e){v.innerHTML='<div class="alert err">Greška: '+esc(e.message||e)+'</div>'})}
function prof(id,force){var v=$('#view');if(!v||!id)return;if(!force&&profile===id&&$('#patientTasksCard'))return;api('/api/care/patients/'+encodeURIComponent(id)+'/tasks?status=open').then(function(d){var old=$('#patientTasksCard');if(old)old.remove();var it=d.items||[],h='';if(!it.length)h='<div class="empty">Nema otvorenih zadataka.</div>';else{h='<div style="display:grid;gap:8px">';for(var i=0;i<it.length;i++)h+=box(it[i],false);h+='</div>'}var c=document.createElement('div');c.className='card';c.id='patientTasksCard';c.innerHTML='<h3>Zadaci za sljedeću posjetu</h3><div class="grid cols-3"><div><label>Zadatak</label><input id="taskTitle"></div><div><label>Prioritet</label><select id="taskPriority"><option value="normal">Normalno</option><option value="high">Visoko</option><option value="low">Nisko</option></select></div><div><label>Rok</label><input id="taskDue" type="datetime-local"></div><div style="grid-column:1/-1"><label>Detalji</label><textarea id="taskDetails" rows="2"></textarea></div></div><div style="margin-top:10px"><button class="btn" id="addTask" type="button">Dodaj zadatak</button></div><div style="margin-top:12px">'+h+'</div>';v.appendChild(c);profile=id;$('#addTask').onclick=function(){api('/api/care/patients/'+encodeURIComponent(id)+'/tasks',{method:'POST',body:{title:val('taskTitle'),details:val('taskDetails'),priority:val('taskPriority'),due_at:val('taskDue')}}).then(function(){profile='';prof(id,true)}).catch(function(e){alert('Greška: '+(e.message||e))})};bind(function(){profile='';prof(id,true)})}).catch(function(e){console.warn('[tasks]',e)})}
function run(){nav();page();if((location.hash||'').split('?')[0]==='#patient'){var id=q().get('id')||'';if(id)prof(id,false)}}
function sched(){if(timer)clearTimeout(timer);timer=setTimeout(run,250)}
window.addEventListener('hashchange',function(){profile='';sched()});document.addEventListener('DOMContentLoaded',sched);try{new MutationObserver(sched).observe(document.documentElement,{childList:true,subtree:true})}catch(e){}if(document.readyState!=='loading')sched();
})();
